version: '3.8'

services:
  densenet-benchmark:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: densenet-benchmark
    environment:
      - CUDA_VISIBLE_DEVICES=0
      - PYTHONUNBUFFERED=1
      - NVIDIA_VISIBLE_DEVICES=all
    volumes:
      - ./results:/app/results
      - ./logs:/app/logs
    runtime: nvidia
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    networks:
      - benchmark-network
    depends_on:
      - tensorboard
    command: >
      sh -c "python3 main.py --output-dir /app/results --gpu-enabled true"

  tensorboard:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: densenet-tensorboard
    ports:
      - "6006:6006"
    volumes:
      - ./logs:/app/logs
      - ./results:/app/results
    networks:
      - benchmark-network
    command: >
      sh -c "tensorboard --logdir=/app/logs/tensorboard --host=0.0.0.0 --port=6006"
    restart: unless-stopped

networks:
  benchmark-network:
    driver: bridge

volumes:
  results:
    driver: local
  logs:
    driver: local