apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: densenet-inference
  namespace: default
spec:
  template:
    metadata:
      annotations:
        # Enable scale-to-zero
        autoscaling.knative.dev/minScale: "1"
        autoscaling.knative.dev/maxScale: "3"
        # Scale down after 30s of no requests
        autoscaling.knative.dev/scale-down-delay: "30s"
        # Target concurrent requests per replica
        autoscaling.knative.dev/target: "10"
        # Resource configuration
        autoscaling.knative.dev/class: "kpa.autoscaling.knative.dev"
    spec:
      containerConcurrency: 10
      containers:
      - name: densenet-inference
        image: devharal/densenet-inference:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080   # 👈 Knative will set $PORT=8080 automatically
        resources:
          requests:
            cpu: "100m"
            memory: "512Mi"
          limits:
            cpu: "1000m"
            memory: "2Gi"
        # Health checks
        readinessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 10
          periodSeconds: 5
          timeoutSeconds: 5
          successThreshold: 1
          failureThreshold: 3
        livenessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 15
          periodSeconds: 10
          timeoutSeconds: 5
          successThreshold: 1
          failureThreshold: 3
